spring:
  application:
    name: inv-service
  datasource:
    url: jdbc:h2:mem:products-db
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/BDCC_REALM_TEST
          jwk-set-uri: http://localhost:8180/realms/BDCC_REALM_TEST/protocol/openid-connect/certs

server:
  port: 8087
